//This Shery code is not typed by hand. 
//It is generated by Shery Editor. 
//I just selected my preferred effects and copied the code.
Shery.imageEffect("#back", {style: 5, config:{
    "a":{"value":2.75,"range":[0,30]},
    "b":{"value":-0.95,"range":[-1,1]},
    "zindex":{"value":-9996999,"range":[-9999999,9999999]},
    "aspect":{"value":2.0658498256530407},
    "ignoreShapeAspect":{"value":true},
    "shapePosition":{"value":{"x":0,"y":0}},
    "shapeScale":{"value":{"x":0.5,"y":0.5}},
    "shapeEdgeSoftness":{"value":0,"range":[0,0.5]},
    "shapeRadius":{"value":0,"range":[0,2]},
    "currentScroll":{"value":0},
    "scrollLerp":{"value":0.07},
    "gooey":{"value":true},
    "infiniteGooey":{"value":true},
    "growSize":{"value":7.52,"range":[1,15]},
    "durationOut":{"value":1,"range":[0.1,5]},
    "durationIn":{"value":1.5,"range":[0.1,5]},
    "displaceAmount":{"value":0.5},
    "masker":{"value":true},
    "maskVal":{"value":1.27,"range":[1,5]},
    "scrollType":{"value":0},
    "geoVertex":{"range":[1,64],"value":1},
    "noEffectGooey":{"value":false},
    "onMouse":{"value":1},
    "noise_speed":{"value":0.38,"range":[0,10]},
    "metaball":{"value":0.2,"range":[0,2],"_gsap":{"id":3}},
    "discard_threshold":{"value":0.5,"range":[0,1]},
    "antialias_threshold":{"value":0,"range":[0,0.1]},
    "noise_height":{"value":0.5,"range":[0,2]},
    "noise_scale":{"value":10,"range":[0,100]}},
    gooey: true});

//Now comes the part to animate the text

let elems = document.querySelectorAll(".elem");

elems.forEach(function(elem){ //we use forEach to target h1s in each elem div
    let h1s = elem.querySelectorAll("h1");
    let index = 0;
    let animate = false;
    document.querySelector("#back").addEventListener("click", function(){
        if(!animate){
            animate = true;
            gsap.to(h1s[index],{
                top: "-=100%",
                ease: Expo.easeInOut,
                duration: 1,
                onComplete: function(){ //moving the h1 which moved up to the bottom
                    gsap.set(this._targets[0],{ top: "100%" }); //we use this to know which h1 must be moved to the bottom
                    animate = false 
                }
            });
            
            index++;
        
            index === h1s.length ? (index = 0) : index; //checks if index is equal to h1s.length, if yes, index = 0, else index = index
        
            gsap.to(h1s[index],{
                top: "-=100%",
                ease: Expo.easeInOut,
                duration: 1
            });
        }
        
    });
});


